package com.hotel.models.enums;

public enum TipoEvento {
    CREACION_RESERVA,
    MODIFICACION_RESERVA,
    ELIMINACION_RESERVA,
    CREACION_ESTANCIA,
    ACTIVACION_ESTANCIA,
    MODIFICACION_ESTANCIA,
    ELIMINACION_ESTANCIA,
    FINALIZACION_ESTANCIA,
    CREACION_PAGO,
    MODIFICACION_PAGO,
    ELIMINACION_PAGO
}
